apiVersion: v1
kind: Service
metadata:
  name: deepseek-r1-7b
  labels:
    app: deepseek-r1-7b
spec:
  selector:
    app: deepseek-r1-7b
  ports:
    - protocol: TCP
      port: 8000
      name: http
  type: ClusterIP