apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: nvidia-gpu
spec:
  amiSelectorTerms:
    - alias: al2@latest
  role: deepseek-cluster-karpenter
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: deepseek-cluster
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: deepseek-cluster
  tags:
    karpenter.sh/discovery: deepseek-cluster

  # Enable the node "instance-store" ephemeral storage
  # https://karpenter.sh/docs/concepts/nodeclasses/#specinstancestorepolicy
  instanceStorePolicy: RAID0